### ISSUE TITLE
add news filtre adblock

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [deletescape/noads#3]
Hello,

I just discovered your DNS and I'm quite surprised at how fast it is. I am in France and I would like to know if it is possible to block popups & Ads:

Also, you can add these lists to your DNS server:

-https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/rpz.blacklist

- https://sebsauvage.net/hosts/hosts

Merci

**Comment by nyancrimew** [comment]
I unfortunately cannot block all popups, but only those where the scripts originate from specific origins. I added the two lists to my merge script and they should start being used today or tomorrow
