### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [deletescape/noads#4]
Hello, 

your dns blocks facebook photos and videos so the site remains unusable, so it does not block enough advertising on some websites: 

for example: 

- https://www.ddl-island.co/index.php
- Snapchat (android)

Here are two new filters for your dns that will block many ads, popup and fraudulent site: 

https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

Here is what you need to put on the white list:

https://i.goopics.net/pJeyP.jpg

don't close the conversation, I'll give you more bug reports if I find any other anomalies. 

Merci

**Comment by nyancrimew** [comment]
* The remaining ads on ddl-island cannot be filtered at DNS level
* I'll look into Snapchat again, but I am probably already filtering everything I can at DNS level without breaking the app itself

I just fixed some issues regarding images on instagram, will look into fb now

**Comment by nyancrimew** [comment]
Facebook should be properly working again, and I have added some more lists
