### ISSUE TITLE
You've Removed My Hosts For Blocking Too Much - Any Specific Sites I Should Investigate?

### ISSUE THREAD

**Issue by ghost** [deletescape/noads#5]
Any specific sites I should fix?

https://github.com/deletescape/noads/commit/bcb03c9fd1d8609d257fb8d566c27d67f5f46a05#commitcomment-36236191

**Comment by DRSDavidSoft** [comment]
@Cybo1927 Pardon me for asking, but if I'm not mistaken this is an aggregated list, right? Maybe false positives could be because of included lists in yours?

**Comment by ghost** [comment]
@DRSDavidSoft You saying my list has a lot of false positives and that's why it was removed?

Note: I know I have a decent amount of false positives-it's because I'm only one person and it's not easy to maintain a list as big as mine has gotten. (between 24-25K things)

**Comment by nyancrimew** [comment]
this has been a while ago and I don't remember specifically what was broken, I'll see if I have some time to test it for myself over the next few days

**Comment by ghost** [comment]
@deletescape Okay, thanks!
