### ISSUE TITLE
Your public dns is down, isn't it ?

### ISSUE THREAD

**Issue by imTHAI** [deletescape/noads#6]
Your server is unreachable

% dig @167.99.241.49 google.com +short

; <<>> DiG 9.10.6 <<>> @167.99.241.49 google.com +short
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by nyancrimew** [comment]
yes my public DNS server started having problems so I temporarily shut it down, but haven't had time to get it up again and might keep it down for a little longer. I really need to update my website about this

**Comment by imTHAI** [comment]
Yes. Of course u do It voluntarily and freely, but dns is a service so much crucial for an internet connection. It unfortunately has to be reliable, even we usually configure two servers.
